# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Ethan L'
description:      'Economics and data analytics student. Data analyst. Interested in software development, design, data visualisation.'
url:              http://hyde.getpoole.com
baseurl:          '/'
author:
  name:           'Ethan L'

paginate:         5

github:           https://github.com/EthanVIII

# Gems
gem: [jekyll-paginate, jekyll-gists,redcarpet]

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet