# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Ethan L'
description:      'Data analyst and student. Interested in data visualisation, design, and software development.'
url:              https://ethanviii.github.io
baseurl:          ''
author:
  name:           'Ethan L'

paginate:         5

github:           https://github.com/EthanVIII

# Gems
gem: [jekyll-paginate, jekyll-gists,redcarpet]

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet